#!/bin/bash

set -e
#set -x

if [ $# -eq 2 ]; then
    mount -o noatime,noexec,nosuid,nodev,rw "${1}" "${2}"
    if [ -w "${2}/" ] && [ -f "${2}/autorun.inf" ]; then
        # if it is possible to write on the source partition, remove it.
        mv "${2}/autorun.inf" "${2}/DANGEROUS_autorun.inf_DANGEROUS"
    fi
    mount -o remount,ro "${1}"
    exit 0
else
    echo 'Invalid number of arguments.'
    exit 1
fi
